### ISSUE TITLE
This should fail: <b></ b>

### ISSUE THREAD

**Issue by louisptremblay** [pluralsight/htmlTagValidator#19]
Hi
If there is a space in the closing tag after the slash such as </ b>, it doesn't get detected.

However, Chrome doesn't like it and doesn't consider it as a closing tag

See: 
https://jsfiddle.net/6j0kdL04/

**Comment by aj-foster** [comment]
Hi @louisptremblay 👋🏼 

Thank you for filing this issue so many years ago. We haven't maintained this repo in a long time (as you can tell) so I'm going to transition it to an archived state. I encourage everyone to find (or make!) forks of the code.

Thank you for your support!
