### ISSUE TITLE
Possible to escape tags in a string?

### ISSUE THREAD

**Issue by MJAlonzo** [pluralsight/htmlTagValidator#22]
For example
`<script>
	var str='<div>Some Content</div>';
</script>`
Should be valid but isn't. A workaround, although hacky, is:
`<script>
	var str='<' + 'div>Some Content<'+'/div>';
</script>`
Suggestions?

**Comment by aj-foster** [comment]
Hello @MJAlonzo 👋🏼 

Thank you for filing this issue so many years ago. We haven't maintained this repo in a long time (as you can tell) so I'm going to transition it to an archived state. I encourage everyone to find (or make!) forks of the code.

Thank you for your support!
