### ISSUE TITLE
It should let you use it as a boolean condition

### ISSUE THREAD

**Issue by cbsorrilha** [pluralsight/htmlTagValidator#23]
like this:

```
if (htmlTagValidator(sampleHtml)) {
  console.log("valid");
} else {
  console.log("invalid");
}
```

**Comment by aj-foster** [comment]
Hi @cbsorrilha 👋🏼 

Thank you for filing this issue so many years ago. We haven't maintained this repo in a long time (as you can tell) so I'm going to transition it to an archived state. I encourage everyone to find (or make!) forks of the code.

Thank you for your support!
