### ISSUE TITLE
Allow to specify allowed tags

### ISSUE THREAD

**Issue by mrded** [pluralsight/htmlTagValidator#24]
I think it makes sense to specify allowed tags, so validation will fail if there're other tags used.

**Comment by aj-foster** [comment]
Hello @mrded 👋🏼 

Thank you for filing this issue so many years ago. We haven't maintained this repo in a long time (as you can tell) so I'm going to transition it to an archived state. I encourage everyone to find (or make!) forks of the code.

Thank you for your support!
