### ISSUE TITLE
SVG support?

### ISSUE THREAD

**Issue by lazarljubenovic** [pluralsight/htmlTagValidator#26]
Are SVGs handled? If not, how can I ignore everything under the `<svg>` tag?

I'm getting the following error:

```text
The path tag does not have a d attribute
```

**Comment by denisx** [comment]
plz fix it

**Comment by aj-foster** [comment]
Hi everyone,

Thank you for filing this issue so many years ago. We haven't maintained this repo in a long time (as you can tell) so I'm going to transition it to an archived state. I encourage everyone to find (or make!) forks of the code.

Thank you for your support!
