### ISSUE TITLE
Parse content with too many <br> would lead to crash

### ISSUE THREAD

**Issue by showwell0120** [pluralsight/htmlTagValidator#27]
When the content contains lots of br tags, the checking process would run for so long time, and the page would crash if I don't close it immediately. Is that any infinite loop or other condition that would  lead to such kind of this situation?

here is me code:
````javascript
htmlTagValidator(parsed.content, {
    settings: {
        validateAttributes: false,
        ignoreUnknownAttributes: true
 }}, function(err, ast) {
    // could not run this callback
    console.log('htmlTagValidator: ', err, ast);
});
`````

**Comment by aj-foster** [comment]
Hello @showwell0120 👋🏼 

Thank you for filing this issue. We haven't maintained this repo in a while so I'm going to transition it to an archived state. I encourage everyone to find (or make!) forks of the code.

Thank you for your support!
